# -*- coding: utf-8 -*-
"""OpenCV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WVIHqotG1T921_jc7XyMsHHdqapHr_Ua
"""

#!pip install opencv-python
#!python -m pip install pyserial

import cv2
import numpy as np
import serial
import time

"""# FaceRecognition

"""

def detectFace(img):
    filename = img.split(".")[0] # 取得檔案名稱(不添加副檔名)
    img = cv2.imread(img) # 讀取圖檔
    grayImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # 透過轉換函式轉為灰階影像
    color = (0, 255, 0)  # 定義框的顏色
    
    # OpenCV 人臉識別分類器
    face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 
            "haarcascade_frontalface_default.xml")
    
    # 調用偵測識別人臉函式
    faceRects = face_classifier.detectMultiScale(
        grayImg, scaleFactor=1.25, minNeighbors=2, minSize=(25, 25))
    
    # 大於 0 則檢測到人臉
    if len(faceRects):  
      # 框出每一張人臉
      for faceRect in faceRects: 
        x, y, w, h = faceRect
        cv2.rectangle(img, (x, y), (x + h, y + w), color, 2)
    #print(len(faceRects))
    # 將結果圖片輸出
    cv2.imwrite(filename + "_face.jpg", img)
    
    return len(faceRects)

val = detectFace('S6.jpg')
print(val)

"""# Return Back to Arduoino"""

data_serial = serial.Serial('/dev/cu.usbserial-1120',115200)

def getValue_on():
  
  if val == 1:
    data_serial.write(b'1')
  if val == 2:
    data_serial.write(b'2')
  if val==3:
    data_serial.write(b'3')
  if val >= 4:
    data_serial.write(b'4')
    

while(1):
  getValue_on()
  time.sleep(5)